# config/_default/menus.toml

[[main]]
  name = "Series"
  pageRef = "series"
  weight = 20

[[main]]
  name = "Portfolio"
  url = "https://francescopapini.com"
  weight = 30

[[main]]
  name = "Medium"
  url = "https://medium.com/@francesco_papini"
  weight = 40

[[main]]
  name = "Github"
  url = "https://github.com/papo1011"
  weight = 50

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.
